config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get '/jobs', to: 'jobs#index'

  get '/upload_jobs', to: 'jobs#insert_jobs'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
require 'httparty'

class JobsController < ApplicationController
  before_action :data_url, only: [:insert_jobs]
  API_URL = 'https://enigmatic-meadow-90199.herokuapp.com/'

  def index; end

  def show

  end

  def insert_jobs
    @jobs = @jobs_api['jobs']['job']
    @jobs.each do |job|
      Job.find_or_create_by!(jobId: job['jobId']) do |item|
        item.date = job['date']
        item.jobId = job['jobId']
        item.city = job['city']
        item.state = job['state']
        item.zipcode = job['zipcode']
        item.license = job['license']
        item.specialty = job['specialty']
        item.shift = job['shift']
        item.startdate = job['startdate']
        item.enddate = job['enddate']
        item.description = job['description']
        item.benefits = job['benefits']
        item.requirements = job['requirements']
        item['created_at'] = job['created_at']
        item['updated_at'] = job['updated_at']
      end
    end
    @jobs_list = Job.all
    render json: @jobs_list
  end

  private
  def data_url
    response = HTTParty.get(API_URL)
    json = JSON.parse(response.body)
    @jobs_api = json
  end

end


# t.date "date"
# t.integer "jobId"
# t.string "city"
# t.string "state"
# t.string "zipcode"
# t.string "license"
# t.string "specialty"
# t.string "shift"
# t.date "startdate"
# t.date "enddate"
# t.text "description"
# t.text "benefits"
# t.text "requirements"
# t.datetime "created_at", null: false
# t.datetime "updated_at", null: false

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def about_nora
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<header id="masthead" class="site-header" role="banner">
  <div class="container">
    <div id="brand">
      <h1 class="site-title">
        <a href="http://www.assurednursing.com/" title="Assured Nursing" rel="home">Assured Nursing</a>
      </h1>
    </div>
    <!-- /brand -->
    <div id="mobile-menu">
      <i class="fa fa-bars"></i>
    </div>
    <div class="header-right">
      <div class="header-contact">
        <div class="header-contact-info">
          <i class="fa fa-phone"></i> (317) 862-8141 &nbsp; &nbsp; &nbsp;
          <a href="mailto:staffing@assurednursing.com" target="_blank" class="header-contact-email">
            <i class="fa fa-envelope"></i> staffing@assurednursing.com
          </a>
        </div>
        <a href="https://www.facebook.com/AssuredNursing" target="_blank" class="social">
          <i class="fa fa-facebook"></i>
        </a>
        <a href="https://www.instagram.com/assurednursing/" target="_blank" class="social">
          <i class="fa fa-instagram"></i>
        </a>
        <a href="https://twitter.com/AssuredNursing " target="_blank" class="social">
          <i class="fa fa-twitter"></i>
        </a>
        <a href="http://www.linkedin.com/company/assured-nursing-inc?trk=tyah" target="_blank" class="social">
          <i class="fa fa-linkedin"></i>
        </a>
      </div>
      <nav role="navigation" class="site-navigation main-navigation">
        <div class="menu-menu-1-container">
          <ul id="menu-menu-1" class="menu">
            <li id="menu-item-11" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home menu-item-11">
              <%= link_to 'Home', pages_home_path %>
              <!--<a href="http://www.assurednursing.com/">Home</a>-->
            </li>
            <li id="menu-item-12" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-12">
              <%= link_to 'About Us', pages_about_path  %>
              <!--<a href="http://www.assurednursing.com/about-us/">About Us</a>-->
            </li>
            <li id="menu-item-15" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-15">
              <%= link_to 'Open Positions', jobs_path %>
              <!--<a href="http://jobs.assurednursing.com/jobseeker/SearchResults.aspx?featured=1&#038;runsearch=1">Open Positions</a>-->
            </li>
            <li id="menu-item-13" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-9 current_page_item menu-item-13">
              <%= link_to 'Contact Us', pages_contact_path %>
              <!--<a href="http://www.assurednursing.com/contact-us/">Contact Us</a>-->
            </li>
          </ul>
        </div>
      </nav>
      <!-- .site-navigation .main-navigation -->

    </div>
    <div class="clear"></div>
  </div>
  <!--/container -->


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      Assured Nursing |
      Contact Us</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= evil_icons_sprite %>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" href="/files/2015/10/favicon.ico"/>
    <link rel="profile" href="http://gmpg.org/xfn/11" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href-="app/assets/stylesheets/application.css" />

    <link rel="pingback" href="http://www.assurednursing.com/xmlrpc.php" />
    <!--[if lt IE 9]>
    <script src="http://www.assurednursing.com/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/js/html5.js" type="text/javascript"></script>
    <![endif]-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Yellowtail">
    <link rel='stylesheet' href= '/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/styles/boots-bones.css' type='text/css' media='all' />
    <meta name='robots' content='noindex,follow' />
    <link rel='dns-prefetch' href='//s.w.org' />
    <link rel="alternate" type="application/rss+xml" title="Assured Nursing &raquo; Feed" href="http://www.assurednursing.com/feed/" />
    <link rel="alternate" type="application/rss+xml" title="Assured Nursing &raquo; Comments Feed" href="http://www.assurednursing.com/comments/feed/" />
    <script type="text/javascript">
        window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.4\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.4\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/www.assurednursing.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=a936cebafdae85ac8da0df9ba8eeeca4"}};
        !function(a,b,c){function d(a,b){var c=String.fromCharCode;l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,a),0,0);var d=k.toDataURL();l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,b),0,0);var e=k.toDataURL();return d===e}function e(a){var b;if(!l||!l.fillText)return!1;switch(l.textBaseline="top",l.font="600 32px Arial",a){case"flag":return!(b=d([55356,56826,55356,56819],[55356,56826,8203,55356,56819]))&&(b=d([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]),!b);case"emoji":return b=d([55357,56692,8205,9792,65039],[55357,56692,8203,9792,65039]),!b}return!1}function f(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var g,h,i,j,k=b.createElement("canvas"),l=k.getContext&&k.getContext("2d");for(j=Array("flag","emoji"),c.supports={everything:!0,everythingExceptFlag:!0},i=0;i
        <j.length;i++)c.supports[j[i]]=e(j[i]),c.supports.everything=c.supports.everything&&c.supports[j[i]],"flag"!==j[i]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[j[i]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(h=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",h,!1),a.addEventListener("load",h,!1)):(a.attachEvent("onload",h),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),g=c.source||{},g.concatemoji?f(g.concatemoji):g.wpemoji&&g.twemoji&&(f(g.twemoji),f(g.wpemoji)))}(window,document,window._wpemojiSettings);

    </script>
    <style type="text/css">
      img.wp-smiley,
      img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
      }
    </style>
    <link rel='stylesheet' id='style.css-group-css' href='http://www.assurednursing.com/wp-content/plugins/bwp-minify/min/?f=wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/style.css' type='text/css' media='all' />
    <link rel='https://api.w.org/' href='http://www.assurednursing.com/wp-json/' />
    <link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.assurednursing.com/xmlrpc.php?rsd" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.assurednursing.com/wp-includes/wlwmanifest.xml" />
    <link rel="canonical" href="http://www.assurednursing.com/contact-us/" />
    <link rel='shortlink' href='http://www.assurednursing.com/?p=9' />
    <link rel="alternate" type="application/json+oembed" href="http://www.assurednursing.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fwww.assurednursing.com%2Fcontact-us%2F" />
    <link rel="alternate" type="text/xml+oembed" href="http://www.assurednursing.com/wp-json/oembed/1.0/embed?url=http%3A%2F%2Fwww.assurednursing.com%2Fcontact-us%2F&#038;format=xml" />
    <link rel="icon" href="http://www.assurednursing.com/files/2015/10/cropped-AHC-Guys-32x32.jpg" sizes="32x32" />
    <link rel="icon" href="http://www.assurednursing.com/files/2015/10/cropped-AHC-Guys-192x192.jpg" sizes="192x192" />
    <link rel="apple-touch-icon-precomposed" href="http://www.assurednursing.com/files/2015/10/cropped-AHC-Guys-180x180.jpg" />
    <meta name="msapplication-TileImage" content="http://www.assurednursing.com/files/2015/10/cropped-AHC-Guys-270x270.jpg" />
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<body class="page-template-default page page-id-7">
<!-- #masthead .site-header -->
<div class="bar center">
  <h3 class="second-font">We place nurses in fabulous places!</h3>
  <form id="keyword-state-search" action="http://jobs.assurednursing.com/JobSeeker/SearchResults.aspx" method="post">
    <input name="spKeyword" placeholder="Job Title" id="keyword-search">
    <select name="citystate" id="state-search">
      <option value="">Select State</option>
      <option value="AL">AL</option>
      <option value="AK">AK</option>
      <option value="AZ">AZ</option>
      <option value="AR">AR</option>
      <option value="CA">CA</option>
      <option value="CO">CO</option>
      <option value="CT">CT</option>
      <option value="DE">DE</option>
      <option value="DC">DC</option>
      <option value="FL">FL</option>
      <option value="GA">GA</option>
      <option value="HI">HI</option>
      <option value="ID">ID</option>
      <option value="IL">IL</option>
      <option value="IN">IN</option>
      <option value="IA">IA</option>
      <option value="KS">KS</option>
      <option value="KY">KY</option>
      <option value="LA">LA</option>
      <option value="ME">ME</option>
      <option value="MD">MD</option>
      <option value="MA">MA</option>
      <option value="MI">MI</option>
      <option value="MN">MN</option>
      <option value="MS">MS</option>
      <option value="MO">MO</option>
      <option value="MT">MT</option>
      <option value="NE">NE</option>
      <option value="NV">NV</option>
      <option value="NH">NH</option>
      <option value="NJ">NJ</option>
      <option value="NM">NM</option>
      <option value="NY">NY</option>
      <option value="NC">NC</option>
      <option value="ND">ND</option>
      <option value="OH">OH</option>
      <option value="OK">OK</option>
      <option value="OR">OR</option>
      <option value="PA">PA</option>
      <option value="RI">RI</option>
      <option value="SC">SC</option>
      <option value="SD">SD</option>
      <option value="TN">TN</option>
      <option value="TX">TX</option>
      <option value="UT">UT</option>
      <option value="VT">VT</option>
      <option value="VA">VA</option>
      <option value="WA">WA</option>
      <option value="WV">WV</option>
      <option value="WI">WI</option>
      <option value="WY">WY</option>
    </select>
    <input type="hidden" name="RunSearch" value="1">
    <input type="hidden" name="spSortOrder" value="2">
    <input type="hidden" name="RecordViewCount" value="1000">
    <input id="Submit" type="submit" value="Go!" class="keyword-state-submit">

  </form>
</div>
<div class="main-container">
  <div id="primary">
    <div id="content" role="main" class="span8">
      <article class="post">
        <h1 class="title">About Us</h1>
        <div class="the-content">
          <p>It’s about YOU. Assured Nursing has the reputation of improving the quality of life for our healthcare professionals. Your life changes, employment opportunities change, the industry changes. Assured Nursing has a significant advantage because we know our Nurses and the Opportunities.</p>
          <h2>Our Story</h2>
          <p>Our CEO and Owner Nora Vandagrifft is a nurse. She has worked in hospitals through an agency. She understands both sides of the employment relationship.  
            <a href="http://www.assurednursing.com/about-nora-vandagrifft/">Read more about Nora.</a>
          </p>
          <ul>
            <li>Assured Nursing has been in business since 2001</li>
            <li>We provide staffing for all hospital positions, including:

              <ul>
                <li>Per Diem – Temporary staffing (daily and weekly)</li>
                <li>Contract Staffing – 13 weeks or longer</li>
                <li>Permanent placement and contract to hire</li>
              </ul>
            </li>
            <li>We provide staffing in healthcare facilities throughout the US.</li>
            <li>Some of our nurses have been with us for 15+ years</li>
          </ul>
        </div>
        <!-- the-content -->


      </article>
    </div>
    <!-- #content .site-content -->

  </div>
  <!-- #primary .content-area -->
  <div id="sidebar" role="sidebar">
    <div class="sidebar-widget">
      <h2 class="widgettitle">Default/About Page &#8211; sidebar pic</h2>
      <div class="textwidget">
        <%= image_tag ("sidebar-beach.jpg"), alt: "A picture of a beach." %>
<!--
        <img src="/app/assets/images/sidebar-beach.jpg" alt="A picture of a beach.">
-->
      </div>
    </div>
    <div class="sidebar-widget">
      <div class="textwidget">
        <div class="sidebar-text">
          <p>Our dedication to YOU, combined with our understanding of the opportunities, allow us to make Travel Contracts easy and convenient.</p>
          <a href="http://jobs.assurednursing.com/jobseeker/Profile_Quick.aspx?" target="_blank" class="red button">Submit Your Resume
            <i clarailss="fa fa-arrow-circle-o-right"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <!-- #sidebar -->


</div>
<!-- .main-container -->
<footer class="site-footer" role="contentinfo">
  <div class="container">
    <div class="half left">
      <%= image_tag ("footer-logo.jpg"), alt: "Logo Footer" %>
      <%= image_tag ("footer-logo2.png"), alt: "National Quality Approval" %>
      <%= image_tag ("footer-wbe.png"), alt: "Certified Women's Business Enterprise" %>
      <%= image_tag ("Proud-Exhibitor.png"), alt: "Traveler's Conference Exhibitor" %>
    </div>
    <div class="half right alignright">
      <h4>Give us a call! (317) 862-8141</h4>
      <p>&copy; 2018 Assured Nursing. All Rights Reserved. </p>
    </div>
  </div>
</footer>
<!-- #colophon .site-footer -->
<script type='text/javascript' src='http://www.assurednursing.com/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
<script type='text/javascript' src='http://www.assurednursing.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
<script type='text/javascript' src='http://www.assurednursing.com/wp-content/plugins/bwp-minify/min/?f=wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/js/jquery.fitvids.js,wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/js/theme.min.js,wp-includes/js/wp-embed.min.js'></script>
<link href="/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/map/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/map/jquery.vmap.js" type="text/javascript"></script>
<script src="/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/map/jquery.vmap.usa.js" type="text/javascript"></script>
<script src="/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/map/jqvmap.search.js"  type="text/javascript"></script>
</body>
</html>

app/views/pages/about_nora.html.erb
<body class="page-template-default page page-id-36">
<!-- #masthead .site-header -->
<div class="bar center">
  <h3 class="second-font">We place nurses in fabulous places!</h3>
  <form id="keyword-state-search" action="http://jobs.assurednursing.com/JobSeeker/SearchResults.aspx" method="post">
    <input name="spKeyword" placeholder="Job Title" id="keyword-search">
    <select name="citystate" id="state-search">
      <option value="">Select State</option>
      <option value="AL">AL</option>
      <option value="AK">AK</option>
      <option value="AZ">AZ</option>
      <option value="AR">AR</option>
      <option value="CA">CA</option>
      <option value="CO">CO</option>
      <option value="CT">CT</option>
      <option value="DE">DE</option>
      <option value="DC">DC</option>
      <option value="FL">FL</option>
      <option value="GA">GA</option>
      <option value="HI">HI</option>
      <option value="ID">ID</option>
      <option value="IL">IL</option>
      <option value="IN">IN</option>
      <option value="IA">IA</option>
      <option value="KS">KS</option>
      <option value="KY">KY</option>
      <option value="LA">LA</option>
      <option value="ME">ME</option>
      <option value="MD">MD</option>
      <option value="MA">MA</option>
      <option value="MI">MI</option>
      <option value="MN">MN</option>
      <option value="MS">MS</option>
      <option value="MO">MO</option>
      <option value="MT">MT</option>
      <option value="NE">NE</option>
      <option value="NV">NV</option>
      <option value="NH">NH</option>
      <option value="NJ">NJ</option>
      <option value="NM">NM</option>
      <option value="NY">NY</option>
      <option value="NC">NC</option>
      <option value="ND">ND</option>
      <option value="OH">OH</option>
      <option value="OK">OK</option>
      <option value="OR">OR</option>
      <option value="PA">PA</option>
      <option value="RI">RI</option>
      <option value="SC">SC</option>
      <option value="SD">SD</option>
      <option value="TN">TN</option>
      <option value="TX">TX</option>
      <option value="UT">UT</option>
      <option value="VT">VT</option>
      <option value="VA">VA</option>
      <option value="WA">WA</option>
      <option value="WV">WV</option>
      <option value="WI">WI</option>
      <option value="WY">WY</option>
    </select>
    <input type="hidden" name="RunSearch" value="1">
    <input type="hidden" name="spSortOrder" value="2">
    <input type="hidden" name="RecordViewCount" value="1000">
    <input id="Submit" type="submit" value="Go!" class="keyword-state-submit">

  </form>
</div>
<div class="main-container">
  <div id="primary">
    <div id="content" role="main" class="span8">
      <article class="post">
        <h1 class="title">About Nora Vandagrifft</h1>
        <div class="the-content">
          <p>In 1990-1993 while living in Malawi, Africa, Nora was driving behind a bus loaded with families when the bus tragically slipped over the edge rolling over and seriously injuring many of the passengers. When she returned to the United States, Nora made the decision to become a nurse to help others in a time of medical need.</p>
          <p>Nora Vandagrifft, Assured Nursing’s CEO and Owner, graduated from Indiana University &#8211; Purdue University Indianapolis (IUPUI) with an RN degree. She started her professional career with Community Health in Kokomo, Indiana.</p>
          <p>Nora worked 5pm-5am shifts and later 5am-5pm shifts and was required to work every other weekend. As a single mother of three, she was challenged to keep her life in balance arriving home as the children were leaving for school, then leaving for work as the children were coming home from school. Nora switched to day shift, believing this would improve the situation, only to learn it was difficult finding a day care that opened at 4am. Nora frequently found herself needing two sets of day care to handle the hours. Knowing there had to be a better way she went to work for a nurse staffing agency to provide flexibility for her family.</p>
          <p>In June of 2000 at 1am while working for an agency, Nora received a call from the County Coroner saying that there had been a shooting and she needed to come and identify the body. That night Nora’s 13-year-old son was spending the night with his cousin. The two boys, unbeknown to Nora, decided to spend the night with a friend of the cousin. Nora called the night shift supervisor at the hospital and asked the supervisor to cover the balance of the shift. The supervisor agreed to finish Nora’s shift. Nora then called her agency employer to inform them she would be leaving. Before Nora could leave the unit she received a call from the owner of the agency saying she could not leave, that the shift was the agencies shift and they would lose the money for the shift. Regardless of the death she was expected to stay. Nora told the owner she was leaving and it would be her last day with the agency.</p>
          <p>Tragically it was her nephew who had lost his life that night in a tragic circumstance.</p>
          <p>Nora decided to start her own staffing agency and Assured Nursing, Inc. was formed. Nora wanted to give nurses balance between work and family — the flexibility to live a more fulfilled life.</p>
          <p>Over the next year Nora worked to establish the business, working as a nurse three days a week and spending the other days marketing Assured Nursing. Nora landed her first contract by working at the hospital as a nurse and recruiting nurses in the evenings and on weekends. Fourteen years later, Assured Nursing does business with more than 50 hospitals and surgery centers in Indiana, and has developed partnerships with several physician groups. In February of 2012, Assured Nursing was selected to provide the Indiana Veteran’s Home in Lafayette, Indiana with the Medical Director and team of specialty physicians focused on keeping residents in the facility at home and healthy.</p>
          <p>Assured Nursing, continues to focus on the flexibility to create a balance in life. Assured Nursing received its Joint Commission Certification in December of 2010, followed by the company’s certification as a Women’s Business Enterprise the same month.</p>
        </div>
        <!-- the-content -->


      </article>
    </div>
    <!-- #content .site-content -->

  </div>
  <!-- #primary .content-area -->
  <div id="sidebar" role="sidebar">
    <div class="sidebar-widget">
      <h2 class="widgettitle">Default/About Page &#8211; sidebar pic</h2>
      <div class="textwidget">
        <img src="/files/2015/11/sidebar-beach.jpg" alt="A picture of a beach.">
      </div>
    </div>
    <div class="sidebar-widget">
      <div class="textwidget">
        <div class="sidebar-text">
          <p>Our dedication to YOU, combined with our understanding of the opportunities, allow us to make Travel Contracts easy and convenient.</p>
          <a href="http://jobs.assurednursing.com/jobseeker/Profile_Quick.aspx?" target="_blank" class="red button">Submit Your Resume
            <i class="fa fa-arrow-circle-o-right"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <!-- #sidebar -->


</div>
<!-- .main-container -->
<footer class="site-footer" role="contentinfo">
  <div class="container">
    <div class="half left">
      <img src="/files/2015/10/footer-logo.jpg" alt="Assured Nursing">
      <img src="/files/2015/10/footer-logo2.png" alt="National Quality Approval">
      <img src="/files/2015/10/footer-wbe.png" alt="Certified Women's Business Enterprise">
      <img src="/files/2017/07/Proud-Exhibitor.png" alt="Travelers Conference Exhibitor">

    </div>
    <div class="half right alignright">
      <h4>Give us a call! (317) 862-8141</h4>
      <p>&copy; 2018 Assured Nursing. All Rights Reserved. </p>
    </div>
  </div>
</footer>
<!-- #colophon .site-footer -->
<script type='text/javascript' src='http://www.assurednursing.com/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
<script type='text/javascript' src='http://www.assurednursing.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
<script type='text/javascript' src='http://www.assurednursing.com/wp-content/plugins/bwp-minify/min/?f=wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/js/jquery.fitvids.js,wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/js/theme.min.js,wp-includes/js/wp-embed.min.js'></script>
<i class="fa fa-angle-up" id="lnkBackToTop"></i>
<script type="text/javascript">
    // Back to Top Icon Visibility
    function setBackToTop() {
        jQuery("#lnkBackToTop").toggleClass("visible", (jQuery(window).height() < jQuery(document).height() && jQuery(window).scrollTop() > 0));
    }
    jQuery(document).ready(function() {
        // Mobile Nav
        jQuery('#mobile-menu').click(function() {
            jQuery('.header-right').slideToggle();
        });
        // Back to Top Icon Scrolling
        jQuery(window).on("resize, scroll", setBackToTop);
        jQuery("#lnkBackToTop").on("click", function (e) {
            jQuery("html, body").animate({ scrollTop: 0 }, 500);
            e.preventDefault();
            return false;
        });
        setBackToTop();
    });

</script>
<link href="/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/map/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />
<script src="/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/map/jquery.vmap.js" type="text/javascript"></script>
<script src="/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/map/jquery.vmap.usa.js" type="text/javascript"></script>
<script src="/wp-content/themes/131108-Assurednursing.com/Assured-Nursing-2015/map/jqvmap.search.js"  type="text/javascript"></script>
</body>
</html>